#!/usr/bin/env python3
# ABOUTME: Generates assets/how-it-works.svg, the animated README demo of zsh-ai-prompt.
# ABOUTME: Usage: python3 assets/gen-how-it-works-svg.py assets/how-it-works.svg. Pure SMIL, loops forever.

import sys
from html import escape

T = 14.0          # loop length in seconds
CW = 15.6         # monospace advance at font-size 26 (0.6em)
X_BUF = 34        # buffer start after "❯ "

QUERY = "find all .log files older than 7 days"
ANSWER = 'find . -name "*.log" -type f -mtime +7'   # real claude-haiku-5-5 output
MODEL = "claude-haiku-5-5"

T_ALT = 1.2       # Alt-A pressed
T_TYPE = 2.0      # typing starts
CHAR = 0.07       # seconds per typed character
T_TYPED = T_TYPE + CHAR * len(QUERY)
T_ENTER = T_TYPED + 0.5
T_ANSWER = T_ENTER + 1.9
T_FADE = T - 0.6

INK, MUTED, FAINT = "#4F4D48", "#9A94A8", "#E2DECE"
PROMPT_GREEN, DIR_BLUE, MAGENTA, ACCENT = "#4E9A06", "#0087AF", "#B03A9E", "#D97757"


def kt(t):
    return f"{t / T:.4f}".rstrip("0").rstrip(".") or "0"


def visible(*spans, attr="opacity"):
    """Discrete opacity animation: 1 inside the (start, end) spans, 0 elsewhere."""
    points = [(0.0, "0")]
    for start, end in spans:
        points += [(start, "1"), (end, "0")]
    if points[1][0] == 0.0:
        points = points[1:]
    values = ";".join(v for _, v in points)
    times = ";".join(kt(t) for t, _ in points)
    return (f'<animate attributeName="{attr}" dur="{T}s" repeatCount="indefinite" '
            f'calcMode="discrete" values="{values}" keyTimes="{times}"/>')


def steps(attr, points):
    """Discrete animation of any attribute through (time, value) points."""
    values = ";".join(str(v) for _, v in points)
    times = ";".join(kt(t) for t, _ in points)
    return (f'<animate attributeName="{attr}" dur="{T}s" repeatCount="indefinite" '
            f'calcMode="discrete" values="{values}" keyTimes="{times}"/>')


def fixed_width(chars):
    """Pins a line to CW per character, so the typing clip and the cursor
    line up even when the viewer's monospace font has a different advance."""
    return f' textLength="{chars * CW:.1f}" lengthAdjust="spacingAndGlyphs"'


def text(x, y, s, fill, extra=""):
    return f'<text x="{x}" y="{y}" fill="{fill}"{extra}>{escape(s)}</text>'


ROW_B, ROW_C = 150, 196

# typed query: a clip that widens one character at a time
type_points = [(0.0, 0)] + [(T_TYPE + i * CHAR, round((i + 1) * CW, 1)) for i in range(len(QUERY))]

# cursor position per phase (x, y of the block's top-left)
cur_y = lambda row: row - 24
cursor_x = [(0.0, X_BUF), (T_ALT + 0.2, 0)] + \
           [(T_TYPE + i * CHAR, round((i + 1) * CW, 1)) for i in range(len(QUERY))] + \
           [(T_ENTER, 0), (T_ANSWER, round(X_BUF + len(ANSWER) * CW + 4, 1))]
cursor_y = [(0.0, cur_y(ROW_B)), (T_ALT + 0.2, cur_y(ROW_C)), (T_ANSWER, cur_y(ROW_B))]

SPINNER = "⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏"
spin_dur = 0.8
spinner_glyphs = []
for i, g in enumerate(SPINNER):
    a, b = i / len(SPINNER), (i + 1) / len(SPINNER)
    vals, times = ("1;0", f"0;{b:.2f}") if i == 0 else ("0;1;0", f"0;{a:.2f};{b:.2f}")
    spinner_glyphs.append(
        f'<text x="{X_BUF + 2 * CW:.1f}" y="{ROW_B + 2}" fill="{MAGENTA}" font-size="34" opacity="0">{g}'
        f'<animate attributeName="opacity" dur="{spin_dur}s" repeatCount="indefinite" '
        f'calcMode="discrete" values="{vals}" keyTimes="{times}"/></text>')

indicator_rest = f" AI mode ({MODEL}) — Enter to send, Esc to cancel"
captions = [
    (T_ALT, T_TYPE, "1", "Alt-A opens AI mode"),
    (T_TYPE, T_ENTER, "2", "ask for what you want in plain English"),
    (T_ENTER, T_ANSWER, "3", "Enter sends it to Claude, OpenAI, Gemini, Grok or Ollama"),
    (T_ANSWER, T_FADE, "4", "the command lands in your buffer: Enter runs it, or edit it first"),
]
chips = [(T_ALT, T_ALT + 1.1, "⌥ A", 112), (T_ENTER, T_ENTER + 0.9, "⏎ Enter", 150)]

svg = f'''<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" style="white-space:pre" viewBox="0 0 1536 404" width="100%" role="img" aria-label="A terminal: Alt-A opens AI mode, the user types a request in plain English, presses Enter, a spinner runs, and a shell command replaces the request in the buffer, ready to run" font-family="'SF Mono', Menlo, Consolas, 'DejaVu Sans Mono', monospace" font-size="26">
  <!-- Generated by assets/gen-how-it-works-svg.py; edit that and regenerate. -->
  <title>zsh-ai-prompt: how it works</title>
  <defs>
    <clipPath id="typed"><rect x="0" y="{ROW_C - 30}" width="0" height="40">{steps("width", type_points)}</rect></clipPath>
    <filter id="soft" x="-5%" y="-20%" width="110%" height="140%">
      <feDropShadow dx="0" dy="10" stdDeviation="18" flood-color="#2B2640" flood-opacity="0.12"/>
    </filter>
  </defs>

  <!-- no page background: the window sits on whatever the README renders on -->
  <g transform="translate(96,24)">
    <rect width="1344" height="352" rx="18" fill="#F8F5F1" stroke="{FAINT}" stroke-width="2" filter="url(#soft)"/>
    <circle cx="30" cy="28" r="7" fill="{FAINT}"/>
    <circle cx="54" cy="28" r="7" fill="{FAINT}"/>
    <circle cx="78" cy="28" r="7" fill="{FAINT}"/>

    <g transform="translate(40,0)">
      <!-- powerlevel10k-style two-line prompt -->
      {text(0, 104, "~/projects/api", DIR_BLUE)}
      {text(round(15 * CW, 1), 104, "main", PROMPT_GREEN)}
      {text(0, ROW_B, "❯", PROMPT_GREEN, ' font-weight="700"')}

      <!-- AI mode indicator (PREDISPLAY), between Alt-A and Enter -->
      <g opacity="0">{visible((T_ALT + 0.2, T_ENTER))}
        <text x="{X_BUF}" y="{ROW_B}" fill="{MUTED}"{fixed_width(3 + len(indicator_rest))}>  <tspan fill="{MAGENTA}">⟡</tspan>{escape(indicator_rest)}</text>
      </g>

      <!-- the request, typed on the line below the indicator -->
      <g opacity="0" clip-path="url(#typed)">{visible((T_TYPE, T_ENTER))}
        {text(0, ROW_C, QUERY, INK, fixed_width(len(QUERY)))}
      </g>

      <!-- waiting: spinner in the indicator line -->
      <g opacity="0">{visible((T_ENTER, T_ANSWER))}
        {"".join(spinner_glyphs)}
        {text(round(X_BUF + 4 * CW, 1), ROW_B, "thinking...", MUTED)}
      </g>

      <!-- the answer replaces the buffer, right after the prompt. Base opacity 1
           so a renderer without SMIL still shows the finished state -->
      <g opacity="1">{visible((T_ANSWER, T_FADE))}
        {text(X_BUF, ROW_B, ANSWER, INK, fixed_width(len(ANSWER)))}
      </g>

      <!-- block cursor: moves with the buffer, blinks -->
      <g opacity="0">{visible((0.0, T_FADE))}
        <rect width="14" height="30" fill="{INK}" opacity="0.8">
          {steps("x", cursor_x)}
          {steps("y", cursor_y)}
          <animate attributeName="opacity" values="0.8;0.8;0;0" keyTimes="0;0.5;0.5;1" dur="1s" repeatCount="indefinite"/>
        </rect>
      </g>
    </g>

    <!-- key presses -->
    {"".join(f"""<g opacity="0">{visible((s, e))}
      <rect x="{1344 - 40 - w}" y="166" width="{w}" height="46" rx="10" fill="#FFFFFF" stroke="{FAINT}" stroke-width="2"/>
      <rect x="{1344 - 40 - w}" y="206" width="{w}" height="6" rx="3" fill="{FAINT}"/>
      <text x="{1344 - 40 - w / 2}" y="197" fill="{INK}" font-size="22" text-anchor="middle">{escape(label)}</text>
    </g>
    """ for s, e, label, w in chips)}

    <!-- what is happening, one step at a time -->
    <line x1="40" y1="246" x2="1304" y2="246" stroke="{FAINT}" stroke-width="2"/>
    {"".join(f"""<g opacity="{1 if n == '4' else 0}" font-size="22">{visible((s, e))}
      <circle cx="54" cy="294" r="15" fill="{ACCENT}"/>
      <text x="54" y="301" fill="#FFFFFF" font-size="18" font-weight="700" text-anchor="middle">{n}</text>
      <text x="84" y="302" fill="{INK}">{escape(caption)}</text>
    </g>
    """ for s, e, n, caption in captions)}
  </g>
</svg>
'''

with open(sys.argv[1], "w") as f:
    f.write(svg)
print(f"wrote {sys.argv[1]} ({len(svg)} bytes), loop {T}s, answer at {T_ANSWER:.2f}s")
